# Generated by Django 4.0.4 on 2022-05-15 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginform', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='New_Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name1', models.CharField(max_length=30)),
                ('dept', models.CharField(max_length=30)),
                ('category', models.CharField(max_length=30)),
                ('subject', models.CharField(max_length=30)),
                ('priority', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=30)),
            ],
        ),
    ]
