# Generated by Django 4.0.4 on 2022-05-15 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loginform', '0002_new_ticket'),
    ]

    operations = [
        migrations.RenameField(
            model_name='new_ticket',
            old_name='name1',
            new_name='Name',
        ),
    ]
